/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AnswerEntry {
  isCorrect: boolean;
  text: string;
}

export interface QuestionEntry {
  answers: AnswerEntry[];
  question: string;
}

export type QuizData = QuestionEntry[];

export interface QuizPackage {
  description: string;
  name: string;
  quizData: QuizData;
}

export type QuizPackageList = QuizPackage[];
